-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 11:12:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Veículos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Veículos` (
  `placaCarro` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `ano` YEAR(4) NULL,
  PRIMARY KEY (`placaCarro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casa` (
  `numeroCasa` INT NOT NULL,
  `bloco` VARCHAR(45) NULL,
  `titular` VARCHAR(45) NULL,
  `dependentesTitular` VARCHAR(45) NULL,
  PRIMARY KEY (`numeroCasa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Morador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Morador` (
  `codigoTitular` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `dataNascimento` DATE NULL,
  `rg` VARCHAR(11) NULL,
  `cpf` VARCHAR(15) NULL,
  `imagem` LONGBLOB NULL,
  `email` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `inicioMoradia` VARCHAR(45) NULL,
  `placaCarro` INT NOT NULL,
  `numeroCasa` INT NOT NULL,
  PRIMARY KEY (`codigoTitular`, `placaCarro`, `numeroCasa`),
  INDEX `fk_Morador_Veículos_idx` (`placaCarro` ASC) VISIBLE,
  INDEX `fk_Morador_casa1_idx` (`numeroCasa` ASC) VISIBLE,
  CONSTRAINT `fk_Morador_Veículos`
    FOREIGN KEY (`placaCarro`)
    REFERENCES `Veículos` (`placaCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Morador_casa1`
    FOREIGN KEY (`numeroCasa`)
    REFERENCES `casa` (`numeroCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Visitantes` (
  `rg` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Veículos_placaCarro` INT NOT NULL,
  `casa_numeroCasa` INT NOT NULL,
  PRIMARY KEY (`rg`, `Veículos_placaCarro`, `casa_numeroCasa`),
  INDEX `fk_Visitantes_Veículos1_idx` (`Veículos_placaCarro` ASC) VISIBLE,
  INDEX `fk_Visitantes_casa1_idx` (`casa_numeroCasa` ASC) VISIBLE,
  CONSTRAINT `fk_Visitantes_Veículos1`
    FOREIGN KEY (`Veículos_placaCarro`)
    REFERENCES `Veículos` (`placaCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitantes_casa1`
    FOREIGN KEY (`casa_numeroCasa`)
    REFERENCES `casa` (`numeroCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entregas` (
  `idEntrega` INT NOT NULL,
  `produto` VARCHAR(45) NULL,
  `transportadora` VARCHAR(45) NULL,
  `data` DATETIME(20) NULL,
  `nomeEntregador` VARCHAR(45) NULL,
  `casa_numeroCasa` INT NOT NULL,
  PRIMARY KEY (`idEntrega`, `casa_numeroCasa`),
  INDEX `fk_Entregas_casa1_idx` (`casa_numeroCasa` ASC) VISIBLE,
  CONSTRAINT `fk_Entregas_casa1`
    FOREIGN KEY (`casa_numeroCasa`)
    REFERENCES `casa` (`numeroCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controle de Acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controle de Acesso` (
  `registroEntrada` INT NOT NULL,
  `data` VARCHAR(45) NULL,
  `Visitantes_rg` INT NOT NULL,
  `Visitantes_Veículos_placaCarro` INT NOT NULL,
  `idEntrega` INT NOT NULL,
  PRIMARY KEY (`registroEntrada`, `Visitantes_rg`, `Visitantes_Veículos_placaCarro`, `idEntrega`),
  INDEX `fk_Controle de Acesso_Visitantes1_idx` (`Visitantes_rg` ASC, `Visitantes_Veículos_placaCarro` ASC) VISIBLE,
  INDEX `fk_Controle de Acesso_Entregas1_idx` (`idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Controle de Acesso_Visitantes1`
    FOREIGN KEY (`Visitantes_rg` , `Visitantes_Veículos_placaCarro`)
    REFERENCES `Visitantes` (`rg` , `Veículos_placaCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Controle de Acesso_Entregas1`
    FOREIGN KEY (`idEntrega`)
    REFERENCES `Entregas` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reservas` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
