-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 11:05:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema condoManager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema condoManager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `condoManager` DEFAULT CHARACTER SET utf8 ;
USE `condoManager` ;

-- -----------------------------------------------------
-- Table `condoManager`.`Proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `condoManager`.`Proprietario` (
  `idProprietario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `telefone` VARCHAR(15) NULL,
  `dataNascimento` DATE NULL,
  `dataAquisicao` DATE NULL,
  `cpf` VARCHAR(20) NULL,
  `rg` VARCHAR(15) NULL,
  PRIMARY KEY (`idProprietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `condoManager`.`Casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `condoManager`.`Casa` (
  `numero` INT NOT NULL,
  `bloco` VARCHAR(45) NULL,
  `dataRegistro` DATE NULL,
  `vagas` INT NULL,
  `idProprietario` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_Casa_Proprietario1_idx` (`idProprietario` ASC) VISIBLE,
  CONSTRAINT `fk_Casa_Proprietario1`
    FOREIGN KEY (`idProprietario`)
    REFERENCES `condoManager`.`Proprietario` (`idProprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `condoManager`.`Morador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `condoManager`.`Morador` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `dataNascimento` DATE NULL,
  `rg` VARCHAR(15) NULL,
  `cpf` VARCHAR(20) NULL,
  `imagem` LONGBLOB NULL,
  `email` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `inicioMoradia` VARCHAR(45) NULL,
  `casa` INT NOT NULL,
  PRIMARY KEY (`codigo`, `casa`),
  INDEX `fk_Morador_casa1_idx` (`casa` ASC) VISIBLE,
  CONSTRAINT `fk_Morador_casa1`
    FOREIGN KEY (`casa`)
    REFERENCES `condoManager`.`Casa` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `condoManager`.`Veículos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `condoManager`.`Veículos` (
  `placaCarro` VARCHAR(40) NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `ano` YEAR(4) NULL,
  `casa` INT NOT NULL,
  PRIMARY KEY (`placaCarro`),
  INDEX `fk_Veículos_casa1_idx` (`casa` ASC) VISIBLE,
  CONSTRAINT `fk_Veículos_casa1`
    FOREIGN KEY (`casa`)
    REFERENCES `condoManager`.`Casa` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `condoManager`.`Visitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `condoManager`.`Visitantes` (
  `idVisitante` INT NOT NULL AUTO_INCREMENT,
  `rg` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `idade` INT NULL,
  `celular` VARCHAR(45) NULL,
  PRIMARY KEY (`idVisitante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `condoManager`.`Entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `condoManager`.`Entregas` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `nomeEntregador` VARCHAR(45) NULL,
  `entrega` DATE NULL,
  `horario_entrega` TIME NULL,
  `retirada` DATE NULL,
  `horario_retirada` TIME NULL,
  `status` VARCHAR(45) NULL DEFAULT 'ENTREGUE',
  `observacao` TEXT NULL,
  `casa` INT NOT NULL,
  PRIMARY KEY (`idEntrega`, `casa`),
  INDEX `fk_Entregas_casa1_idx` (`casa` ASC) VISIBLE,
  CONSTRAINT `fk_Entregas_casa1`
    FOREIGN KEY (`casa`)
    REFERENCES `condoManager`.`Casa` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `condoManager`.`Acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `condoManager`.`Acesso` (
  `idAcesso` INT NOT NULL AUTO_INCREMENT,
  `entrada` DATE NULL,
  `saida` DATE NULL,
  `casa` INT NOT NULL,
  `visitante` INT NOT NULL,
  `horario_entrada` TIME NULL,
  `horario_saida` TIME NULL,
  PRIMARY KEY (`idAcesso`),
  INDEX `fk_Controle de Acesso_Casa1_idx` (`casa` ASC) VISIBLE,
  INDEX `fk_Controle de Acesso_Visitantes1_idx` (`visitante` ASC) VISIBLE,
  CONSTRAINT `fk_Controle de Acesso_Casa1`
    FOREIGN KEY (`casa`)
    REFERENCES `condoManager`.`Casa` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Controle de Acesso_Visitantes1`
    FOREIGN KEY (`visitante`)
    REFERENCES `condoManager`.`Visitantes` (`idVisitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `condoManager`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `condoManager`.`usuario` (
  `username` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `tipoUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



insert into usuario (username,senha,tipoUsuario) values ('adm','3196a10252286b4d5976476f1909102ec33048a3e6f14a69b540cee8e1ca97dc','Administrador'); 

INSERT INTO `condoManager`.`Proprietario`
(`telefone`, `rg`, `cpf`, `nome`, `dataNascimento`, `email`)
VALUES
('(11)9876-5432', '33.444.555-6', '123.456.789-09', 'Maria Oliveira', '1985-07-18', 'maria@email.com');

INSERT INTO `condoManager`.`Proprietario`
(`telefone`, `rg`, `cpf`, `nome`, `dataNascimento`, `email`)
VALUES
('(21)8765-4321', '11.222.333-4', '987.654.321-09', 'Pedro Silva', '1970-03-05', 'pedro@email.com');

INSERT INTO `condoManager`.`Proprietario`
(`telefone`, `rg`, `cpf`, `nome`, `dataNascimento`, `email`)
VALUES
('(31)7654-3210', '44.555.666-7', '654.321.987-09', 'Carla Santos', '1992-11-30', 'carla@email.com');

INSERT INTO `condoManager`.`Proprietario`
(`telefone`, `rg`, `cpf`, `nome`, `dataNascimento`, `email`)
VALUES
('(41)6543-2109', '22.333.444-5', '789.012.345-09', 'Ricardo Oliveira', '1982-09-12', 'ricardo@email.com');

INSERT INTO `condoManager`.`Proprietario`
(`telefone`, `rg`, `cpf`, `nome`, `dataNascimento`, `email`)
VALUES
('(51)5432-1098', '66.777.888-3', '012.345.678-90', 'Amanda Silva', '1996-04-08', 'amanda@email.com');

-- CASA 
-- Proprietário 1
INSERT INTO Casa (vagas, idProprietario, numero, dataRegistro, bloco) VALUES (2, 1, 102, '2023-12-06', 'A-22');

-- Proprietário 2
INSERT INTO Casa (vagas, idProprietario, numero, dataRegistro, bloco) VALUES (2, 2, 103, '2023-12-06', 'A-22');

-- Proprietário 3 (já fornecido no seu exemplo)
INSERT INTO Casa (vagas, idProprietario, numero, dataRegistro, bloco) VALUES (2, 3, 101, '2023-12-06', 'A-22');

-- Proprietário 4
INSERT INTO Casa (vagas, idProprietario, numero, dataRegistro, bloco) VALUES (2, 4, 104, '2023-12-06', 'A-22');

-- Proprietário 5
INSERT INTO Casa (vagas, idProprietario, numero, dataRegistro, bloco) VALUES (2, 5, 105, '2023-12-06', 'A-22');


-- PEDIR MAIS 5
INSERT INTO Morador (casa,telefone,rg,cpf,celular,nome,dataNascimento,email,inicioMoradia) VALUES  (101,'(16)3312-1612','56.123.014-0','506.412.511-23','(16)99711-2154','Pedro CArlos','2000-12-10','pedrocarlos@email.com','2006-10-20')

-- pedir mais 5

INSERT INTO Veículos (marca,placaCarro,tipo,casa,ano,cor,modelo) VALUES  ('Honda','ABC-1234','Carro',101,'2023','Prata','Civic')
com base nesse insert, gere mais 4 parecidos, com as casas 102,103,104,105

INSERT INTO `condoManager`.`Veículos`
(`placaCarro`,
`modelo`,
`marca`,
`tipo`,
`cor`,
`ano`,
`casa`)
VALUES
('FEP-0955',
'Focus',
'Ford',
'Carro',
'Preto',
'2024',
44);




