/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;

import controller.ProprietarioListener;
import java.awt.event.WindowEvent;
import model.Casa;
import model.Proprietario;
import utils.StringUtils;

/**
 * @author Afonso
 */
public class FrmCasaForm extends javax.swing.JFrame {

   private Casa data;
   private boolean      disconnectOnClose;
   private boolean      formEdicao;
   
   private int idProprietario;
  
   public FrmCasaForm(Casa data, boolean disconnectOnClose, boolean formEdicao) {
      initComponents();
      fieldProprietario.setEditable(false);
      
      formataCampos();
      this.formEdicao = formEdicao;
      
      if( this.formEdicao ){
         // this.jTextFieldCpf.setEnabled( false );
      }
      else{
         this.btnSalvar.setText( "Incluir" );
      }

      if( data == null ){
         this.data = new Casa();
      }
      else{
         this.data = data;
         fillFields();
      }
      this.disconnectOnClose = disconnectOnClose;
   }

   private void formataCampos() {
//      fieldNome.setDocument( new FormataTextInput( 50, FormataTextInput.TipoEntrada.NOME ) );
//      fieldEmail.setDocument( new FormataTextInput( 50, FormataTextInput.TipoEntrada.EMAIL ) );

   }


   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldProprietario = new utils.TextField();
        cMButton1 = new utils.CMButton();
        fieldNumero = new utils.TextField();
        fieldVagas = new utils.TextField();
        fieldBloco = new utils.TextField();
        btnSalvar = new utils.CMButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldProprietario.setLabelText("Proprietário");

        cMButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pesquisa.png"))); // NOI18N
        cMButton1.setRadius(25);
        cMButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMButton1ActionPerformed(evt);
            }
        });

        fieldNumero.setLabelText("Número");

        fieldVagas.setLabelText("Vagas");

        fieldBloco.setLabelText("Bloco");

        btnSalvar.setText("Salvar");
        btnSalvar.setRadius(25);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cMButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(fieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(fieldVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cMButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       
         try{
         dataDown();
         data.save();
         this.dispatchEvent( new WindowEvent( this, WindowEvent.WINDOW_CLOSING ) );
      }
      catch( Exception e ){
         e.printStackTrace();
      }
    }//GEN-LAST:event_btnSalvarActionPerformed

     private void fillFields() {

      fieldBloco.setText(data.getBloco());
      fieldNumero.setText( String.valueOf(data.getNumero()));
      fieldProprietario.setText( String.valueOf(data.getIdProprietario()));
      fieldVagas.setText(String.valueOf( data.getVagas()));
   }


   private void dataDown() {

      data.setBloco(fieldBloco.getText() );
      data.setNumero(Integer.parseInt(fieldNumero.getText()) );
      data.setVagas(Integer.parseInt(fieldVagas.getText()) );
      
      if (!formEdicao){
           data.setDataRegistro(StringUtils.getCurrentDateMySQLFormat() );
      }else {
    	  data.setIdProprietario( idProprietario );
      }
     
   }

   private void cMButton1ActionPerformed( java.awt.event.ActionEvent evt ) {// GEN-FIRST:event_cMButton1ActionPerformed
      // TODO add your handling code here:
      FrmProprietariosGrid grid;
      try{
         grid = new FrmProprietariosGrid( true, false );
         grid.setVisible( true );
         grid.setListener( new ProprietarioListener() {
            @Override
            public void getLinhaSelecionadaProprietario( int codigo, String nome ) {
               idProprietario = codigo;
               fieldProprietario.setText(codigo + " - " + nome);
            }
         } );

      }
      catch( SQLException e ){
         e.printStackTrace();
      }
   }// GEN-LAST:event_cMButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.CMButton btnSalvar;
    private utils.CMButton cMButton1;
    private utils.TextField fieldBloco;
    private utils.TextField fieldNumero;
    private utils.TextField fieldProprietario;
    private utils.TextField fieldVagas;
    // End of variables declaration//GEN-END:variables
}
