/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

import model.Usuario;

/**
 *
 * @author aluno
 */
public class FrmMenuNovo extends javax.swing.JFrame {

    Usuario usuario;
    JPopupMenu opcoesUsuario;
    JMenuItem ver, sair;
    
    
    /**
     * Creates new form FrmMenu
     */
    public FrmMenuNovo(Usuario usuario) {
        
    	initComponents();
    	
    	opcoesUsuario = new JPopupMenu();
    	ver = new JMenuItem("Ver");
    	
        this.usuario = usuario;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonMinimizar = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonAcesso = new javax.swing.JButton();
        jButtonEntrega = new javax.swing.JButton();
        jButtonProprietario = new javax.swing.JButton();
        jButtonCasa = new javax.swing.JButton();
        jButtonMorador = new javax.swing.JButton();
        jButtonCarro = new javax.swing.JButton();
        jButtonVisitante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LOGOCM128.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(128, 128));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 128, 128);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CondoManager.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(468, 30, 668, 120);

        jButtonMinimizar.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jButtonMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMinimizar.setText("_");
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonMinimizar);
        jButtonMinimizar.setBounds(1560, -10, 10, 30);

        jButtonSair.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("X");
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSairMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSair);
        jButtonSair.setBounds(1580, 5, 11, 15);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(1490, 60, 75, 22);

        jButtonAcesso.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jButtonAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu/acesso.png"))); // NOI18N
        jButtonAcesso.setText("Acesso");
        jButtonAcesso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAcesso.setIconTextGap(0);
        jButtonAcesso.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonAcesso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessoActionPerformed(evt);
            }
        });

        jButtonEntrega.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jButtonEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu/caixa.png"))); // NOI18N
        jButtonEntrega.setText("Entrega");
        jButtonEntrega.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEntrega.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntregaActionPerformed(evt);
            }
        });

        jButtonProprietario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jButtonProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu/proprietario.png"))); // NOI18N
        jButtonProprietario.setText("Proprietário");
        jButtonProprietario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProprietario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProprietarioActionPerformed(evt);
            }
        });

        jButtonCasa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jButtonCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu/casa-limpa.png"))); // NOI18N
        jButtonCasa.setText("Casa");
        jButtonCasa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCasa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCasaActionPerformed(evt);
            }
        });

        jButtonMorador.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jButtonMorador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu/morador.png"))); // NOI18N
        jButtonMorador.setText("Morador");
        jButtonMorador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMorador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoradorActionPerformed(evt);
            }
        });

        jButtonCarro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jButtonCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu/carro.png"))); // NOI18N
        jButtonCarro.setText("Veículos");
        jButtonCarro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCarro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarroActionPerformed(evt);
            }
        });

        jButtonVisitante.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jButtonVisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu/visitante.png"))); // NOI18N
        jButtonVisitante.setText("Visitante");
        jButtonVisitante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVisitante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisitanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(200, 200, 200)
                            .addComponent(jButtonProprietario))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMorador)
                    .addComponent(jButtonCasa)
                    .addComponent(jButtonProprietario))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVisitante)
                    .addComponent(jButtonAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEntrega))
                .addGap(104, 104, 104)
                .addComponent(jButtonCarro)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessoActionPerformed
       try {
      
        FrmAcessosGrid AcessoGrid = new FrmAcessosGrid(false, true);
        AcessoGrid.setVisible(true);
        
        } catch (Exception ex) {
        ex.printStackTrace();   
      }
    }//GEN-LAST:event_jButtonAcessoActionPerformed

    private void jButtonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonMinimizarMouseClicked

    private void jButtonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseClicked
    	 System.exit(0);
    }//GEN-LAST:event_jButtonSairMouseClicked

    private void jButtonMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoradorActionPerformed
        try {
        FrmMoradoresGrid FrmMoradorGrid = new FrmMoradoresGrid(false, true);
        FrmMoradorGrid.setVisible(true);
        } catch (Exception ex) {
        ex.printStackTrace();   
      }
    }//GEN-LAST:event_jButtonMoradorActionPerformed

    private void jButtonCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCasaActionPerformed
         try {
        FrmCasasGrid FrmCasaGrid = new FrmCasasGrid(null,false, true);
        FrmCasaGrid.setVisible(true);
        } catch (Exception ex) {
        ex.printStackTrace();   
      }
    }//GEN-LAST:event_jButtonCasaActionPerformed

    private void jButtonVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisitanteActionPerformed
        try {
        FrmVisitantesGrid FrmVisitanteGrid = new FrmVisitantesGrid(null,false, true);
        FrmVisitanteGrid.setVisible(true);
        } catch (Exception ex) {
        ex.printStackTrace();   
      }
    }//GEN-LAST:event_jButtonVisitanteActionPerformed

    private void jButtonCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarroActionPerformed
        try {
         FrmVeiculosGrid  FrmVeiculosGrid = new  FrmVeiculosGrid(false, true);
         FrmVeiculosGrid.setVisible(true);
        } catch (Exception ex) {
        ex.printStackTrace();   
      }
    }//GEN-LAST:event_jButtonCarroActionPerformed

    private void jButtonProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProprietarioActionPerformed
          try {
        FrmProprietariosGrid FrmProprietarioGrid = new FrmProprietariosGrid(null,false, true);
        FrmProprietarioGrid.setVisible(true);
        } catch (Exception ex) {
        ex.printStackTrace();   
      }
    }//GEN-LAST:event_jButtonProprietarioActionPerformed

    private void jButtonEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntregaActionPerformed
        try {
        FrmEntregasGrid FrmEntregasGrid = new FrmEntregasGrid(false, true);
        FrmEntregasGrid.setVisible(true);
        } catch (Exception ex) {
        ex.printStackTrace();   
      }
    }//GEN-LAST:event_jButtonEntregaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuNovo(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAcesso;
    private javax.swing.JButton jButtonCarro;
    private javax.swing.JButton jButtonCasa;
    private javax.swing.JButton jButtonEntrega;
    private javax.swing.JLabel jButtonMinimizar;
    private javax.swing.JButton jButtonMorador;
    private javax.swing.JButton jButtonProprietario;
    private javax.swing.JLabel jButtonSair;
    private javax.swing.JButton jButtonVisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
