/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.WindowEvent;

import controller.LogTracker;
import model.Usuario;
import model.Visitante;
import utils.FormataTextInput;
import utils.RegexUtils;
import utils.StringUtils;

/**
 * @author Afonso
 */
public class FrmUsuarioForm extends javax.swing.JFrame {

   private Usuario data;
   private boolean   disconnectOnClose;
   private boolean   formEdicao;

   public FrmUsuarioForm( Usuario data, boolean disconnectOnClose, boolean formEdicao ) {
      initComponents();

      this.formEdicao = formEdicao;

      // jTextFieldNome.setDocument( new FormataTextInput( 10, FormataTextInput.TipoEntrada.NOME ) );

      if( this.formEdicao ){
         // this.jTextFieldCpf.setEnabled( false );
      }
      else{
         this.btnSalvar.setText( "Incluir" );
      }

      if( data == null ){
         this.data = new Usuario();
      }
      else{
         this.data = data;
         fillFields();
      }
      this.disconnectOnClose = disconnectOnClose;
   }




   private void checkInput() throws Exception {

      if( StringUtils.isEmpty( fieldUsername.getText().trim() ) ){
         fieldUsername.setError();
         fieldUsername.requestFocus();
         throw new Exception( "Digite o username" );
      }
      if( StringUtils.isEmpty( fieldSenha.getText().trim() ) ){
    	  fieldSenha.setError();
    	  fieldSenha.requestFocus();
          throw new Exception( "Digite uma senha" );
       }


     

   }


   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldUsername = new design.TextField();
        btnSalvar = new design.CMButton();
        fieldSenha = new design.PasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fieldUsername.setLabelText("Username");

        btnSalvar.setText("Salvar");
        btnSalvar.setRadius(25);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        fieldSenha.setBackground(new java.awt.Color(214, 217, 223));
        fieldSenha.setLabelText("Senha");
        fieldSenha.setShowAndHide(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(fieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


   private void btnSalvarActionPerformed( java.awt.event.ActionEvent evt ) {// GEN-FIRST:event_btnSalvarActionPerformed
      try{
         checkInput();
         dataDown();
         data.save();
         this.dispatchEvent( new WindowEvent( this, WindowEvent.WINDOW_CLOSING ) );
      }
      catch( Exception e ){
         LogTracker.getInstance().addException( e, true, null );
      }
   }// GEN-LAST:event_btnSalvarActionPerformed


   private void fillFields() {

      fieldUsername.setText( data.getUsername() );
      fieldSenha.setText( data.getSenha() );
   }


   private void dataDown() {

      data.setUsername( fieldUsername.getText() );
      data.setSenha( fieldSenha.getText() );
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private design.CMButton btnSalvar;
    private design.PasswordField fieldSenha;
    private design.TextField fieldUsername;
    // End of variables declaration//GEN-END:variables
}
