/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LogTracker;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

import model.Proprietario;
import model.Visitante;
import utils.FormataTextInput;
import utils.RegexUtils;
import utils.StringUtils;

/**
 * @author Afonso
 */
public class FrmVisitanteForm extends javax.swing.JFrame {

   private Visitante data;
   private boolean   disconnectOnClose;
   private boolean   formEdicao;

   public FrmVisitanteForm( Visitante data, boolean disconnectOnClose, boolean formEdicao ) {
      initComponents();

      this.formEdicao = formEdicao;

      // jTextFieldNome.setDocument( new FormataTextInput( 10, FormataTextInput.TipoEntrada.NOME ) );
      setFormatoCampos();

      if( this.formEdicao ){
         // this.jTextFieldCpf.setEnabled( false );
      }
      else{
         this.btnSalvar.setText( "Incluir" );
      }

      if( data == null ){
         this.data = new Visitante();
      }
      else{
         this.data = data;
         fillFields();
      }
      this.disconnectOnClose = disconnectOnClose;
   }


   private void setFormatoCampos() {
      fieldNome.setDocument( new FormataTextInput( 50, FormataTextInput.TipoEntrada.NOME ) );
      fieldIdade.setDocument( new FormataTextInput( 4, FormataTextInput.TipoEntrada.NUMEROINTEIRO ) );
      fieldRg.setDocument( new FormataTextInput( 12, FormataTextInput.TipoEntrada.RG ) );
      fieldCelular.setDocument( new FormataTextInput( 14, FormataTextInput.TipoEntrada.CELULAR ) );

   }


   private void checkInput() throws Exception {

      if( StringUtils.isEmpty( fieldNome.getText().trim() ) ){
         fieldNome.setError();
         fieldNome.requestFocus();
         throw new Exception( "Digite o nome do visitante" );
      }

      if( StringUtils.isEmpty( fieldRg.getText().trim() ) || !fieldRg.getText().matches( RegexUtils.RG ) ){
         fieldRg.setError();
         fieldRg.requestFocus();
         throw new Exception( "O RG deve estar no formato XX.XXX.XXX-X." );
      }

      if( StringUtils.isEmpty( fieldIdade.getText().trim() ) ){
         fieldIdade.setError();
         fieldIdade.requestFocus();
         throw new Exception( "Digite a idade do visitante" );
      }

      if( !fieldCelular.getText().trim().matches( RegexUtils.CELULAR ) ){
         fieldCelular.setError();
         fieldCelular.requestFocus();
         throw new Exception( "O Telefone deve estar no formato '(XX)XXXXX-XXXX'." );
      }

   }


   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings( "unchecked" )
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      fieldNome = new design.TextField();
      fieldIdade = new design.TextField();
      fieldRg = new design.TextField();
      fieldCelular = new design.TextField();
      btnSalvar = new design.CMButton();

      setDefaultCloseOperation( javax.swing.WindowConstants.DISPOSE_ON_CLOSE );

      fieldNome.setLabelText( "Nome" );

      fieldIdade.setLabelText( "Idade" );

      fieldRg.setLabelText( "RG" );

      fieldCelular.setLabelText( "Celular" );

      btnSalvar.setText( "Salvar" );
      btnSalvar.setRadius( 25 );
      btnSalvar.addActionListener( new java.awt.event.ActionListener() {
         public void actionPerformed( java.awt.event.ActionEvent evt ) {
            btnSalvarActionPerformed( evt );
         }
      } );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
      getContentPane().setLayout( layout );
      layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup( layout.createSequentialGroup().addGap( 33, 33, 33 ).addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addComponent( btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE ).addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING, false ).addComponent( fieldNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE ).addComponent( fieldRg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ).addComponent( fieldCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addComponent( fieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addContainerGap( 47, Short.MAX_VALUE ) ) );
      layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup( layout.createSequentialGroup().addGap( 27, 27, 27 ).addComponent( fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 22, 22, 22 ).addComponent( fieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 23, 23, 23 ).addComponent( fieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 28, 28, 28 ).addComponent( fieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ).addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE ).addComponent( btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 51, 51, 51 ) ) );

      pack();
      setLocationRelativeTo( null );
   }// </editor-fold>//GEN-END:initComponents


   private void btnSalvarActionPerformed( java.awt.event.ActionEvent evt ) {// GEN-FIRST:event_btnSalvarActionPerformed
      try{
         checkInput();
         dataDown();
         data.save();
         this.dispatchEvent( new WindowEvent( this, WindowEvent.WINDOW_CLOSING ) );
      }
      catch( Exception e ){
         LogTracker.getInstance().addException( e, true, null );
      }
   }// GEN-LAST:event_btnSalvarActionPerformed


   private void fillFields() {

      fieldNome.setText( data.getNome() );
      fieldRg.setText( data.getRg() );
      fieldCelular.setText( data.getCelular() );
      fieldIdade.setText( String.valueOf( data.getIdade() ) );
   }


   private void dataDown() {

      data.setNome( fieldNome.getText() );
      data.setRg( fieldRg.getText() );
      data.setIdade( Integer.parseInt( fieldIdade.getText() ) );
      data.setCelular( fieldCelular.getText() );
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private design.CMButton  btnSalvar;
   private design.TextField fieldCelular;
   private design.TextField fieldIdade;
   private design.TextField fieldNome;
   private design.TextField fieldRg;
   // End of variables declaration//GEN-END:variables
}
