/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.WindowEvent;
import java.sql.SQLException;

import model.Casa;
import model.Veiculos;

/**
 * @author Afonso
 */
public class FrmVeiculoForm extends javax.swing.JFrame {

   private Veiculos veiculo;
   private boolean  disconnectOnClose;
   private boolean  formEdicao;

   private Casa     casa;

   public FrmVeiculoForm( Veiculos veiculo, boolean disconnectOnClose, boolean formEdicao ) throws SQLException, Exception {
      initComponents();
      fieldCasa.setEditable( false );

      formataCampos();
      this.formEdicao = formEdicao;

      if( this.formEdicao ){
         // this.jTextFieldCpf.setEnabled( false );
      }
      else{
         this.btnSalvar.setText( "Incluir" );
      }

      if( veiculo == null ){
         this.veiculo = new Veiculos();
      }
      else{
         this.veiculo = veiculo;

         if( this.veiculo.getCasa() != null ){
            this.casa = new Casa();
            this.casa.setNumero( this.veiculo.getCasa().getNumero() );
            this.casa.load();
         }

         fillFields();
      }
      this.disconnectOnClose = disconnectOnClose;
   }


   private void formataCampos() {
      // fieldNome.setDocument( new FormataTextInput( 50, FormataTextInput.TipoEntrada.NOME ) );
      // fieldEmail.setDocument( new FormataTextInput( 50, FormataTextInput.TipoEntrada.EMAIL ) );

   }


   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings( "unchecked" )
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      fieldCasa = new utils.TextField();
      cMSelecionar = new utils.CMButton();
      fieldModelo = new utils.TextField();
      fieldAno = new utils.TextField();
      fieldPlaca = new utils.TextField();
      btnSalvar = new utils.CMButton();
      fieldMarca = new utils.TextField();
      fieldTipo = new utils.TextField();
      fieldCor = new utils.TextField();

      setDefaultCloseOperation( javax.swing.WindowConstants.DISPOSE_ON_CLOSE );
      setTitle( "Cadastro Veículos" );

      fieldCasa.setLabelText( "Casa" );

      cMSelecionar.setIcon( new javax.swing.ImageIcon( getClass().getResource( "/resources/pesquisa.png" ) ) ); // NOI18N
      cMSelecionar.setRadius( 25 );
      cMSelecionar.addActionListener( new java.awt.event.ActionListener() {
         public void actionPerformed( java.awt.event.ActionEvent evt ) {
            cMSelecionarActionPerformed( evt );
         }
      } );

      fieldModelo.setLabelText( "Modelo" );

      fieldAno.setLabelText( "Ano" );

      fieldPlaca.setLabelText( "Placa" );

      btnSalvar.setText( "Salvar" );
      btnSalvar.setRadius( 25 );
      btnSalvar.addActionListener( new java.awt.event.ActionListener() {
         public void actionPerformed( java.awt.event.ActionEvent evt ) {
            btnSalvarActionPerformed( evt );
         }
      } );

      fieldMarca.setLabelText( "Marca" );

      fieldTipo.setLabelText( "Tipo" );

      fieldCor.setLabelText( "Cor" );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
      getContentPane().setLayout( layout );
      layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup( layout.createSequentialGroup().addGap( 46, 46, 46 ).addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addComponent( fieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE ).addGroup( layout.createSequentialGroup().addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addComponent( btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE ).addGroup( layout.createSequentialGroup().addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING, false ).addComponent( fieldCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ).addComponent( fieldCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE ) ).addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( cMSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 18, 18, 18 ).addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING, false ).addComponent( fieldAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ).addComponent( fieldPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE ) ) ) ).addGap( 23, 23, 23 ).addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING, false ).addComponent( fieldModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE ).addComponent( fieldTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) ) ) ).addContainerGap( 221, Short.MAX_VALUE ) ) );
      layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup( layout.createSequentialGroup().addGap( 40, 40, 40 ).addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING, false ).addComponent( cMSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ).addComponent( fieldCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) ).addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( fieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ).addComponent( fieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ) ).addGap( 53, 53, 53 ).addGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( fieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ).addComponent( fieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ).addComponent( fieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 45, 45, 45 ).addComponent( fieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ).addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE ).addComponent( btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 82, 82, 82 ) ) );

      pack();
      setLocationRelativeTo( null );
   }// </editor-fold>//GEN-END:initComponents


   private void btnSalvarActionPerformed( java.awt.event.ActionEvent evt ) {// GEN-FIRST:event_btnSalvarActionPerformed

      try{
         dataDown();
         veiculo.save();
         this.dispatchEvent( new WindowEvent( this, WindowEvent.WINDOW_CLOSING ) );
      }
      catch( Exception e ){
         e.printStackTrace();
      }
   }// GEN-LAST:event_btnSalvarActionPerformed


   private void fillFields() {

      fieldAno.setText( veiculo.getAno() );
      fieldCor.setText( veiculo.getCor() );
      fieldMarca.setText( veiculo.getMarca() );
      fieldModelo.setText( veiculo.getModelo() );
      fieldPlaca.setText( veiculo.getPlacaCarro() );
      fieldTipo.setText( veiculo.getTipo() );
      fieldCasa.setText( String.valueOf( veiculo.getCasa().getNumero() ) );
   }


   private void dataDown() throws Exception {

      veiculo.setAno( fieldAno.getText() );

      veiculo.setCor( fieldCor.getText() );
      veiculo.setMarca( fieldMarca.getText() );
      veiculo.setModelo( fieldModelo.getText() );
      veiculo.setPlacaCarro( fieldPlaca.getText() );
      veiculo.setTipo( fieldTipo.getText() );
      veiculo.setCasa( casa );

   }


   private void cMSelecionarActionPerformed( java.awt.event.ActionEvent evt ) {// GEN-FIRST:event_cMButton1ActionPerformed

      try{

         if( casa == null ){
            casa = new Casa();
         }

         FrmCasasGrid casasConsulta;
         casasConsulta = new FrmCasasGrid( casa, true, false );

         casasConsulta.addWindowListener( new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed( java.awt.event.WindowEvent evt ) {
               if( casa.getNumero() > 0 ){
                  fieldCasa.setText( String.valueOf( casa.getNumero() ) );
               }
            }
         } );

         casasConsulta.setVisible( true );
      }
      catch( Exception ex ){
         ex.printStackTrace();
         casa = null;
      }

   }// GEN-LAST:event_cMButton1ActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private utils.CMButton  btnSalvar;
   private utils.CMButton  cMSelecionar;
   private utils.TextField fieldAno;
   private utils.TextField fieldCasa;
   private utils.TextField fieldCor;
   private utils.TextField fieldMarca;
   private utils.TextField fieldModelo;
   private utils.TextField fieldPlaca;
   private utils.TextField fieldTipo;
   // End of variables declaration//GEN-END:variables
}
